#!/usr/bin/env bash

modis=" \
Find:$HOME/.local/bin/rofi-modi-find, \
Web search:$HOME/.local/bin/rofi-modi-websearch \
"

rofi -modi "drun,$modis,window" \
     -show drun -sort -i -disable-history -drun-match-fields "name" -sidebar-mode


exit 0
